name: hydro
channels:
  - conda-forge
dependencies:
  - python=3.8
  - jupyterlab
  - nodejs
  - numpy
  - matplotlib
  - pandas
  - xarray
  - dask
  - cartopy
  - netCDF4
  - rasterio
  - geopandas
  - shapely
  - pyproj
  - jupyter
  - geojson
  - pandas
  - seaborn
  - pysheds
  - mapclassify
  - descartes
  - openpyxl
  - ffmpeg
  - tqdm
  - spyder-kernels
  - scipy
  - statsmodels
  - scikit-learn
  - spyder
  - xlsxwriter
